###
POST http://localhost:9002/profile/Pierre
Content-Type: application/json

{
  "pseudo": "Pierre",
  "biography": "",
  "contactable": true
}

###
PATCH http://localhost:9002/profile/Pierre
Content-Type: application/json

{
  "pseudo": "Pierre",
  "biography": "I am a student at Vinci",
  "contactable": false
}



###
GET http://localhost:9002/profile


###
GET http://localhost:9002/profile/Thomas


###
PATCH http://localhost:9002/profile/Thomas
Content-Type: application/json

{
  "pseudo": "Thomas",
  "biography": "I am a student at Vinci",
  "contactable": true
}

###
GET http://localhost:9002/profile/Lara

###
DELETE http://localhost:9002/profile/Pierre
