openapi: 3.0.0
info:
  title: Contact Service API
  version: 1.0.0
servers:
  - url: http://localhost:9004
paths:
  /contacts:
    post:
      summary: Send a contact request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                senderId:
                  type: string
                receiverId:
                  type: string
      responses:
        '201':
          description: Contact request sent
        '400':
          description: Something get wrong
  /contacts/{senderId}/{stateContact}:
    get:
      summary: Get contacts by senderId and status
      parameters:
        - name: senderId
          in: path
          required: true
          schema:
            type: string
        - name: stateContact
          in: path
          required: true
          schema:
            type: string
            enum: [active, closed]
      responses:
        '200':
          description: Contacts found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
        '404':
          description: Contacts not found
  /contacts/{senderId}/{receiverId}:
    get:
      summary: Get contact by senderId and receiverId
      parameters:
        - name: senderId
          in: path
          required: true
          schema:
            type: string
        - name: receiverId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Contact found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '404':
          description: Contact not found
    patch:
      summary: Update contact status
      parameters:
        - name: contactId
          in: path
          required: true
          schema:
            type: string
        - name: receiverId
          in: path
          required: true
          schema:
            type: string
        - status: status
          in: requestBody
          required: true
          schema:
            type: object
            properties:
              status:
                type: string
                enum: [active, closed]
      responses:
        '200':
          description: Contact status updated
        '400':
          description: Something get wrong
components:
  schemas:
    Contact:
      type: object
      properties:
        idContact:
          type: integer
        senderId:
          type: string
        receiverId:
          type: string
        status:
          type: string
          enum: [pending, active, closed]
