openapi: 3.0.0
info:
  title: Message Service
  description: This service manages sending and retrieving messages between users.
    Users can send messages to each other, and retrieve messages they have sent or received.
    This service works in conjunction with the User Service and Contact Service to ensure that messages are sent to valid users.
  version: 1.0.0
servers:
  - url: http://localhost:9005
paths:
  /messages:
    post:
      summary: Send a message
      description: This endpoint allows sending a message from one user to another.
      requestBody:
        description: A MessagePosted object is expected as input.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessagePosted'
      responses:
        '201':
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Error in sending the message
        '404':
          description: any right contact found
        '401':
            description: Unauthorized to send message because any valid contact

  /messages/{pseudo}:
    get:
      summary: Retrieve a user's messages
      description: This endpoint allows retrieving all messages sent or received by a user.
      parameters:
        - name: pseudo
          in: path
          description: The pseudo of the user whose messages are to be retrieved
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '404':
          description: No messages found for this user
        '400':
            description: Error in retrieving messages - missing pseudo or invalid pseudo

components:
  schemas:
    MessagePosted:
      type: object
      description: Represents a message to be sent
      properties:
        senderPseudo:
          type: string
          description: The pseudo of the user sending the message
        receiverPseudo:
          type: string
          description: The pseudo of the user receiving the message
        message:
          type: string
          description: The content of the message
      required:
        - senderPseudo
        - receiverPseudo
        - message
      example:
        senderPseudo: Alice
        receiverPseudo: Bob
        message: Hi Bob, how are you?

    Message:
      type: object
      description: Represents a message in the system
      properties:
        id:
          type: integer
          description: The unique identifier of the message
        senderPseudo:
          type: string
          description: The pseudo of the user who sent the message
        receiverPseudo:
          type: string
          description: The pseudo of the user who received the message
        message:
          type: string
          description: The content of the message
        timestamp:
          type: string
          format: date-time
          description: The timestamp of when the message was sent
      required:
        - id
        - senderPseudo
        - receiverPseudo
        - message
        - timestamp
      example:
        id: 1
        senderPseudo: Alice
        receiverPseudo: Bob
        message: Hi Bob, how are you?
        timestamp: 1723656252493
