openapi: 3.0.0
info:
  title: Profile Service
  version: 1.0.0
servers:
  - url: http://localhost:9002
paths:
  /profiles/{userId}:
    get:
      summary: Get profile by user ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Profile details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: Profile not found
    post:
      summary: Create profile by user ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          description: Profile created
        '400':
          description: Something get wrong
        '409':
            description: Profile already exists
    patch:
      summary: Update profile by user ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          description: Profile updated
        '400':
          description: Something get wrong
        '404':
          description: Profile not found
    delete:
      summary: Delete profile by user ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Profile deleted
        '404':
          description: Profile not found
        '400':
          description: Something get wrong

components:
  schemas:
    Profile:
      type: object
      properties:
        pseudo:
          type: string
        biography:
          type: string
        contactable:
          type: boolean
