###
POST http://localhost:9004/contact
Content-Type: application/json

{
  "senderPseudo": "Thomas",
    "receiverPseudo": "Lara"
}

###
GET http://localhost:9004/getList/Thomas/PENDING

###
GET http://localhost:9004/Thomas/Lara

###
PATCH http://localhost:9004/Thomas/Lara/ACTIVE
