
#### Register a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "pseudo": "Thomas",
  "gender": "MALE",
  "birthdate": "1993-08-01",
  "birthCountry": "Belgium",
  "motherTongue": "French",
  "contactable": false,
  "password": "123456"
}

#### Connect the user "Thomas"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
"pseudo": "Thomas",
"password": "123456"
}

> {% client.global.set("token", response.body) %}


#### Register a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "pseudo": "Lara",
  "gender": "FEMALE",
  "birthdate": "1997-5-22",
  "birthCountry": "Belgium",
  "motherTongue": "French",
  "biography": "I am a student at Vinci",
  "contactable": true,
  "password": "MotDePasseTest"
}

#### Register a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "pseudo": "Mélanie",
  "gender": "FEMALE",
  "birthdate": "1985-6-12",
  "birthCountry": "Belgium",
  "motherTongue": "French",
  "biography": "I am a student at Vinci",
  "contactable": true,
  "password": "MotDePasseTest"
}

#### Register a new user
POST http://localhost:8080/users
Content-Type: application/json

{
"pseudo": "Lucas",
"gender": "MALE",
"birthdate": "1990-03-15",
"birthCountry": "France",
"motherTongue": "French",
"biography": "Passionate about technology and travel",
"contactable": true,
"password": "Password123"
}

#### Register a new user
POST http://localhost:8080/users
Content-Type: application/json

{
"pseudo": "Sophie",
"gender": "FEMALE",
"birthdate": "1988-12-01",
"birthCountry": "Canada",
"motherTongue": "French",
"biography": "Graphic designer and art lover",
"contactable": false,
"password": "Artistic2021"
}

#### Register a new user
POST http://localhost:8080/users
Content-Type: application/json

{
"pseudo": "Maxime",
"gender": "MALE",
"birthdate": "1995-04-18",
"birthCountry": "Switzerland",
"motherTongue": "French",
"biography": "Outdoor enthusiast and photographer",
"contactable": true,
"password": "OutdoorLife95"
}

#### Register a new user
POST http://localhost:8080/users
Content-Type: application/json

{
"pseudo": "Elodie",
"gender": "FEMALE",
"birthdate": "1992-09-25",
"birthCountry": "Luxembourg",
"motherTongue": "French",
"biography": "Music teacher and singer",
"contactable": true,
"password": "MusicLover92"
}

#### Register a new user
POST http://localhost:8080/users
Content-Type: application/json

{
"pseudo": "Julien",
"gender": "MALE",
"birthdate": "1987-11-30",
"birthCountry": "Belgium",
"motherTongue": "French",
"biography": "Chef and culinary explorer",
"contactable": false,
"password": "CulinaryPassion87"
}



### update user to make it contactable
PUT http://localhost:8080/users/Thomas
Authorization: {{token}}
Content-Type: application/json

{
  "biography": "I am a student at IPL",
  "contactable": true
}



#### Get a user
GET http://localhost:8080/users/Thomas

#### Get all users
GET http://localhost:8080/users


### Create a message which fails because the sender is not a contact of the receiver
POST http://localhost:8080/messages
Authorization: {{token}}
Content-Type: application/json

{
  "senderPseudo": "Thomas",
  "receiverPseudo": "Lara",
  "message": "Hello Lara, how are you?"
}

### Create a contact request
POST http://localhost:8080/contact
Authorization: {{token}}
Content-Type: application/json

{
  "senderPseudo": "Thomas",
  "receiverPseudo": "Lara"
}

### Get list of pending contact requests for a user
GET http://localhost:8080/getList/Thomas/PENDING
Authorization: {{token}}

### Get a contact between two users
GET http://localhost:8080/Lara/Thomas
Authorization: {{token}}

### verify the oposite of the previous request works
GET http://localhost:8080/Thomas/Lara
Authorization: {{token}}

### Change contact status to ACTIVE
PUT http://localhost:8080/Thomas/Lara/ACTIVE
Authorization: {{token}}



#### Connect the user "Lara"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Lara",
  "password": "MotDePasseTest"
}

> {% client.global.set("token", response.body) %}

### Get list of pending contact requests for a user
GET http://localhost:8080/getList/Lara/ACTIVE
Authorization: {{token}}

### Create a message
POST http://localhost:8080/messages
Authorization: {{token}}
Content-Type: application/json


{
  "senderPseudo": "Lara",
  "receiverPseudo": "Thomas",
  "message": "Hello Thomas, I am fine, thank you. And you?"
}

#### Connect the user "Thomas"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Thomas",
  "password": "123456"
}

> {% client.global.set("token", response.body) %}


### Create a message
POST http://localhost:8080/messages
Authorization: {{token}}
Content-Type: application/json

{
  "senderPseudo": "Thomas",
  "receiverPseudo": "Lara",
  "message": "I am fine too, thank you. What are you doing?"
}

#### Connect the user "Lara"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Lara",
  "password": "MotDePasseTest"
}

> {% client.global.set("token", response.body) %}

### Create a message
POST http://localhost:8080/messages
Authorization: {{token}}
Content-Type: application/json

{
  "senderPseudo": "Lara",
  "receiverPseudo": "Thomas",
  "message": "I am studying for my exams. And you?"
}

#### Connect the user "Thomas"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Thomas",
  "password": "123456"
}

> {% client.global.set("token", response.body) %}

### Create a message
POST http://localhost:8080/messages
Authorization: {{token}}
Content-Type: application/json

{
  "senderPseudo": "Thomas",
  "receiverPseudo": "Lara",
  "message": "I am working on my project. Do you want to meet?"
}

#### Connect the user "Lara"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Lara",
  "password": "MotDePasseTest"
}

> {% client.global.set("token", response.body) %}

### Create a message
POST http://localhost:8080/messages
Authorization: {{token}}
Content-Type: application/json

{
  "senderPseudo": "Lara",
  "receiverPseudo": "Thomas",
  "message": "Yes, I would like to meet you. When?"
}

### Get all messages for a user
GET http://localhost:8080/messages/Lara
Authorization: {{token}}




#### Connect the user "Elodie"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Elodie",
  "password": "MusicLover92"
}

> {% client.global.set("token", response.body) %}

### update user to make it uncontactable
PUT http://localhost:8080/users/Elodie
Authorization: {{token}}
Content-Type: application/json

{
  "biography": "Music teacher and singer",
  "contactable": false
}

#### Connect the user "Lucas"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Lucas",
  "password": "Password123"
}

> {% client.global.set("token", response.body) %}


### Create a contact request with someone uncontactable (401)
POST http://localhost:8080/contact
Authorization: {{token}}
Content-Type: application/json

{
  "senderPseudo": "Lucas",
  "receiverPseudo": "Sophie"
}


### Get all messages for a user with any message
GET http://localhost:8080/messages/Lucas
Authorization: {{token}}


#### Connect the user "Thomas"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Thomas",
  "password": "123456"
}

> {% client.global.set("token", response.body) %}

### attempt to create a contact request with someone whom exists a contact request (409)
POST http://localhost:8080/contact
Authorization: {{token}}
Content-Type: application/json

{
  "senderPseudo": "Thomas",
  "receiverPseudo": "Lara"
}


### search users by gender

GET http://localhost:9003/search/Thomas?gender=FEMALE
Authorization: {{token}}


### search users by mother tongue
GET http://localhost:9003/search/Thomas?motherTongue=French
Authorization: {{token}}

### search users with minimum age of 25
GET http://localhost:9003/search/Thomas?minAge=25
Authorization: {{token}}

### search users with maximum age of 30
GET http://localhost:9003/search/Thomas?maxAge=30
Authorization: {{token}}

### search users between ages 25 and 30
GET http://localhost:9003/search/Thomas?minAge=25&maxAge=30
Authorization: {{token}}

### search users by gender and birth country
GET http://localhost:9003/search/Thomas?gender=FEMALE&birthCountry=Belgium
Authorization: {{token}}

### search users by gender, age range, and mother tongue
GET http://localhost:9003/search/Thomas?gender=MALE&minAge=25&maxAge=30&motherTongue=French
Authorization: {{token}}


#### Connect the user "Lara"
POST http://localhost:8080/authentication/connect
Content-Type: application/json

{
  "pseudo": "Lara",
  "password": "MotDePasseTest"
}

> {% client.global.set("token", response.body) %}


### search users by birth country
GET http://localhost:9003/search/Lara?birthCountry=Belgium
Authorization: {{token}}

