### Create Credentials : 200 et 409
POST http://localhost:9007/authentication/Thomas
Content-Type: application/json

{
  "pseudo": "Thomas",
  "password": "123456"
}

### Create Credentials : 400
POST http://localhost:9007/authentication/user
Content-Type: application/json

{
  "pseudo": "user"
}

### Update Credentials : 200
PUT http://localhost:9007/authentication/user
Content-Type: application/json

{
  "username": "user",
  "password": "userupdated"
}

### Update Credentials : 404
PUT http://localhost:9007/authentication/user
Content-Type: application/json

{
  "username": "user2",
  "password": "userupdated"
}

### Update Credentials : 400
PUT http://localhost:9007/authentication/user
Content-Type: application/json

{
  "username": "user2",
  "password": "userupdated"
}

### Delete Credentials : 200
DELETE http://localhost:9007/authentication/user

### Delete Credentials : 404
DELETE http://localhost:9007/authentication/user

### Connect user : 200
POST http://localhost:9007/authentication/connect
Content-Type: application/json

{
  "username": "Thomas",
  "password": "123456"
}

### Connect user : 400
POST http://localhost:9007/authentication/connect
Content-Type: application/json

{
  "username": "user"
}

### Connect user : 200
POST http://localhost:9007/authentication/connect
Content-Type: application/json

{
  "username": "Thomas",
  "password": "123456"
}

### Verify token
POST http://localhost:9007/authentication/verify
Content-Type: application/json

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJhdXRoMCIsInVzZXJuYW1lIjoidXNlciJ9.o7daRuHYcqrWXFXDpfi_wKr3lp53pZayezdssXBLwhu8gRfSEwog-tzTKgMdi-7-FMUpZiuvgaTRYefdhuzsbg
